# Generated by Django 4.2 on 2023-04-30 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_team_is_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="team",
            name="leader",
        ),
        migrations.RemoveField(
            model_name="team",
            name="members",
        ),
        migrations.CreateModel(
            name="Participant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("MEMBER", "MEMBER"), ("LEADER", "LEADER")],
                        default="MEMBER",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "PENDING"),
                            ("APPLIED", "APPLIED"),
                            ("KICKED", "KICKED"),
                            ("LEFT", "LEFT"),
                        ],
                        default="PENDING",
                        max_length=100,
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.team"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.manuscriptuser",
                    ),
                ),
            ],
        ),
    ]
