# Generated by Django 3.2.18 on 2023-04-30 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20230430_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='status',
            field=models.CharField(default='success', max_length=20),
        ),
    ]
