# Generated by Django 4.2 on 2023-04-15 10:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Event",
        ),
    ]
