# Generated by Django 4.2 on 2023-04-15 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0005_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app.manuscriptuser"
            ),
        ),
        migrations.RemoveField(
            model_name="event",
            name="tags",
        ),
        migrations.DeleteModel(
            name="EventTag",
        ),
        migrations.AddField(
            model_name="event",
            name="tags",
            field=models.JSONField(default=list),
        ),
    ]
