PENDING_STATUS = 'PENDING'
APPLIED_STATUS = 'APPLIED'
DECLINED_STATUS = 'DECLINED'
PARTICIPANT_STATUSES = (PENDING_STATUS, APPLIED_STATUS, DECLINED_STATUS)
MEMBER_ROLE = 'MEMBER'
LEADER_ROLE = 'LEADER'
PARTICIPANT_ROLES = (
    (MEMBER_ROLE, MEMBER_ROLE),
    (LEADER_ROLE, LEADER_ROLE),
)
